# Generated by Django 5.0 on 2023-12-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fos',
            field=models.TextField(default='fos not available'),
        ),
    ]
