# Generated by Django 5.0 on 2023-12-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_fos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fos',
            field=models.TextField(default='{ fos not available }'),
        ),
    ]
